name: ios-opencv4
# on: [pull_request, workflow_dispatch]
on:
  push:
    tags:
      - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
  IOS_DEPLOYMENT_TARGET: '9.0'
  MAC_DEPLOYMENT_TARGET: '10.9'
  MAC_ARM64_DEPLOYMENT_TARGET: '11.0'
  ENABLE_BITCODE: OFF
  ENABLE_ARC: OFF
  ENABLE_VISIBILITY: OFF
  EMSCRIPTEN_VERSION: 3.1.28

permissions:
  contents: read

jobs:
  setup:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  mobile-opencv4:
    runs-on: macos-12
    env:
      OPENCV_VERSION: 4.8.0
      PACKAGENAME: opencv-mobile-4.8.0
    steps:
    - uses: actions/checkout@v3
    - name: opencv-source
      run: |
        wget -q https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.zip -O opencv-${{ env.OPENCV_VERSION }}.zip
        unzip -q opencv-${{ env.OPENCV_VERSION }}.zip
    - name: build-arm64
      run: |
        cd opencv-${{ env.OPENCV_VERSION }}
        python3 platforms/apple/build_xcframework.py \
        --iphoneos_deployment_target 9.0 \
        --disable-swift --disable-bitcode \
        --build_only_specified_archs \
        --iphoneos_archs arm64 \
        --iphonesimulator_archs arm64,x86_64 \
        --without contrib \
        --without gapi \
        --without gpu \
        --without highgui \
        --without java \
        --without js \
        --without legacy \
        --without ml \
        --without nonfree \
        --without objc \
        --without photo \
        --without python \
        --without stitching \
        --without ts \
        --without video \
        --without videoio \
        --without videostab \
        --without world \
        --disable PROTOBUF \
        --disable WEBP \
        --disable PNG \
        --disable TIFF \
        --disable OPENJPEG \
        --disable QUIRC \
        --disable IPP \
        --out build
    - name: package
      run: |
        cd opencv-${{ env.OPENCV_VERSION }}/build
        zip -9yr ../../${{ env.PACKAGENAME }}.zip opencv2.xcframework
    - name: upload-zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip

  release:
    permissions:
      contents: write
    needs: [setup, mobile-opencv4]
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: create-release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ needs.setup.outputs.VERSION }}
        name: Release ${{ needs.setup.outputs.VERSION }}
        files: artifacts/*/*.zip
